config/routes.rb
Rails.application.routes.draw do
  resources :players
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bet#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :player
  belongs_to :roulette
  
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :bets, :dependent => :destroy
  validates :name, :presence => true, :uniqueness => true
end

app/models/roulette.rb
class Roulette < ApplicationRecord
  has_many :bets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bet_controller.rb
class BetController < ApplicationController
  include PlayersHelper
  include BetHelper

  def index
      @bets = Bet.all
    #game_simulation
  end

  def save_game_data(player_id, player_bet, player_color, roulette_id, player_gain)
    Bet.create(player_id: player_id, player_bet: player_bet, player_color: player_color, roulette_id: roulette_id, player_gain: player_gain)
  end

  def get_roulette_id(roulette_color)
    if Roulette.all.count == 0
        roulette = Roulette.create(game_number: 1, game_color: roulette_color)
        return roulette.id
    else
      roulette_number = Roulette.all.last.game_number
      roulette = Roulette.create(game_number: (roulette_number+1), game_color: roulette_color)
      return roulette.id
    end
  end

  def game_simulation
    roulette_color = get_color
    roulette_id = get_roulette_id(roulette_color)
    player_id_array.each do |player_id|
      player = Player.find(player_id)
      player_bet = player_bet_amount(player)
      player_color = get_color
      player_gain = gain(player_color,roulette_color,player_bet)
      update_money_earnings(player, player_gain)
      save_game_data(player_id, player_bet, player_color, roulette_id, player_gain)
    end
    puts "paso por game_simulation"
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]
  include PlayersHelper

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    #create a player with base money
    params[:player][:money] = 10000
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :money)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bet_helper.rb
module BetHelper

  def get_color
    random_number = rand(1..100)
    if random_number.between?(1,49)
      return "red"
    elsif random_number.between?(50,98)
      return "black"
    else
      return "green"
    end
  end

  def gain(player_color, roulette_color, player_bet)
    if player_color == roulette_color 
      if player_color == "green"
        return player_bet*15
      else
        return player_bet*2
      end
    end
    return 0
  end

end

app/helpers/players_helper.rb
module PlayersHelper

  def player_bet_amount(player)
    temperature = 26
    player_money = player.money
    if player_money == 0
      return 0
    elsif player_money < 1000
      update_bet_money(player, player_money)
      return player_money
    elsif temperature > 25
      money_bet = ((rand(3..7)/100.0)*player_money).to_i
      update_bet_money(player, money_bet)
      return money_bet
    else
      money_bet = ((rand(8..15)/100.0)*player_money).to_i
      update_bet_money(player, money_bet)
    return money_bet
    end
  end

  def update_bet_money(player, money_bet)
    player.money -= money_bet
    player.save
  end

  def update_money_earnings(player, money_earning)
    player.money += money_earning
    player.save
  end

  def player_id_array
    id_array = []
    Player.all.each do |p|
      id_array.append(p.id)
    end
    return id_array
  end

end

app/views/bet/index.html.erb
<h1>Betting Room</h1>
<div style="margin:100px">
  <table>
    <tbody>
      <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Number of Game</th>
        <th scope="col">Name</th>
        <th scope="col">Money Bet</th>
        <th scope="col">Player Color</th>
        <th scope="col">Roulette Color</th>
        <th scope="col">Player Gain</th>
      </tr>
    </thead>
    <tbody>
      <% @bets.each do |bet| %>
        <tr>
          <td><%= bet.roulette.game_number %></td>
          <td><%= bet.player.name %></td>
          <td><%= bet.player_bet %></td>
          <td><%= bet.player_color %></td>
          <td><%= bet.roulette.game_color %></td>
          <td><%= bet.player_gain %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nnodesroulette</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#" >
        <%= image_tag("gaming.png", size:"30x30") %>
         Roulette Game
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Betting Room <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="players">Player <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <% if !player.new_record? %>
    <div class="field">
      <%= form.label :money %>
      <%= form.number_field :money %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>
<div style="margin:100px">
  <table>
    <tbody>
      <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Money</th>
        <th scope="col">Data</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= player.name %></td>
          <td><%= player.money %></td>
          <td><%= link_to 'Show', player %></td>
          <td><%= link_to 'Edit', edit_player_path(player) %></td>
          <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Estas seguro? hacer esto eliminara al jugador junto a sus jugadas' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <button type="button" class="btn btn-outline-primary"><%= link_to 'New Player', new_player_path %></button>
</div>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Money:</strong>
  <%= @player.money %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>